version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: comigotech
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: comigotech-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/comigotech
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
